
import Header from "@/componets/layout/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className="antialised text-gray-500 "
      >
        <Header />
        <main>
 {children}
        </main>
       
      </body>
    </html>
  );
}
